### ISSUE TITLE
Pre-req script fails on multiple onmicrosoft.com domains

### ISSUE THREAD

**Issue by aidancopps** [o365soa/soa#1]
Running Install-SOAPrerequisites fails on the Application check when the Azure AD tenant has multiple *.onmicrosoft.com domain names present. This is resolved by adding “| Select-Object -First 1" to lines 341 and 1703 where the Get-AzureADDomain command is called.

**Comment by cammurray** [comment]
Thanks @aidancopps this is actually what I figured was going on, but I didn't have any data to support it. I assume you're getting errors showing that the authority needs to be in URI format?

That command is being ran in order to figure out the tenant domain, which is used in token requests with the ADAL library.

I'm thinking though, that the following is potentially a more suitable command to be running:

`Get-AzureADDomain | Where-Object {$_.IsInitial -eq $True}`

Are you able to see if that returns back the correct onmicrosoft.com domain for your tenant?

**Comment by aidancopps** [comment]
Yes I was getting the authority needs to be URI error. Changing lines 340 and 1702 to the below returns the correct domain and works perfectly.

`$tenantdomain = (Get-AzureADDomain | Where-Object {$_.IsInitial -eq $true}).Name`

**Comment by cammurray** [comment]
Fixed in 0.3.1

Pull request #2
