### ISSUE TITLE
Issue with Skype

### ISSUE THREAD

**Issue by BrianKnipfel** [o365soa/soa#19]
I'm running the Install-SOAPrerequisites and getting error after SPO logon....any help? 
FYI, using MFA
and i can logon with this....
Import-Module SkypeOnlineConnector
$sfbSession = New-CsOnlineSession
Import-PSSession $sfbSession

BUT fails running your script.

**09/18/2020 16:13:21 Connecting to SharePoint Online..**
09/18/2020 16:13:37 Connecting to Skype...
Get-CsPowerShellEndpoint : The remote name could not be resolved: 'lyncdiscover.cooperators.onmicrosoft.com'
At C:\Program Files\Common Files\Skype for Business
Online\Modules\SkypeOnlineConnector\SkypeOnlineConnectorStartup.psm1:107 char:26
+ ...      $targetUri = Get-CsPowerShellEndpoint -TargetDomain $adminDomain
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CsPowerShellEndpoint], WebException
    + FullyQualifiedErrorId : System.Net.WebException,Microsoft.Rtc.Management.OnlineConnector.GetPowerShellEndpointCm
   dlet

**Comment by sbueffel** [comment]
Connecting to Skype is one the more common connections with issues due to module dowload and installation, removal of old versions, the target domain, proxy, etc.  Now that more Skype cmdlets have been added to the Teams module, we will be looking at the viability of leveraging that module for the Skype cmdlets and removing any dependency/need for the Skype MSI module.  If you are continuing to have any issues, please reopen this comment or contacting the customer engineer who will be delivering your Security Optimization Assessment.

**Comment by BrianKnipfel** [comment]
we had to hard code it for the module to run pointing to skype with the PFE
