### ISSUE TITLE
Start-Process <URI> does not work in VSCode or Powershell ISE

### ISSUE THREAD

**Issue by ryguy25** [o365soa/soa#4]
In SOA-Prerequisites.psm1 (line 646):  ... Start-Process $Location

You can query the default http handler in the registry for the path to the executable as below.

New-PSDrive -Name HKCR -PSProvider Registry -Root HKEY_Classes_Root | Out-Null
$defaultBrowser = (Get-ItemProperty HKCR:\http\shell\open\command).'(default)'.Split('"')[1]
Start-Process $defaultBrowser $Location

**Comment by sbueffel** [comment]
The collection script that is used by SOA is not supported in PS ISE (because of underlying lack of support by one or more of the M365 workload modules, at least at one time; I would need to check for the latest for each module).  Therefore, it makes sense for us to add code to disallow running this in the ISE, like the collection script does, for consistency.
