### ISSUE TITLE
$AzureADApp = Get-MgApplication -Filter "displayName eq 'Office 3 ...

### ISSUE THREAD

**Issue by GoliatMB** [o365soa/soa#89]
Hi,
I have analyzed the code but I do not see that it searches for the name of the application "Office 3... In the code I see that it creates and searches for the name of the application "Microsoft Security Assessment". I launch only Install-SOAPrerequisites in a test cloud .

---------------------------------------------------------------
Get-MgApplication : One or more errors have occurred.
is C:\Program
Files\WindowsPowerShell\Modules\SOA\3.1.6\SOA-Prerequisites.psm1: 1655
Carácter: 5
+     $AzureADApp = Get-MgApplication -Filter "displayName eq 'Office 3
...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgApplication_List],
    AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Graph.P
   owerShell.Cmdlets.GetMgApplication_List
-----------------------------------------------------------------

**Comment by sbueffel** [comment]
The main branch of the module in GitHub is a version that has not yet been published to PS Gallery. The method to get the application using 3.1.6 from PS Gallery uses the display name, while the version that is in GitHub (and will be published to PS Gallery after other updates have been completed) uses a redirect URI as a filter because of the changed name of the application that will be included in the upcoming publishing.
